export const TOGGLE_LOG = "TOGGLE_LOG";
export const SET_UE_EVENT = "SET_UE_EVENT";
export const SET_OE_EVENT = "SET_OE_EVENT";
export const SET_CURRENT_PURCHASE = "SET_CURRENT_PURCHASE"
export const CLEAR_CURRENT_PURCHASE = "CLEAR_CURRENT_PURCHASE"


export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
