export const TOGGLE_LOG = "TOGGLE_LOG";
export const SET_UE_EVENT = "SET_UE_EVENT";
export const SET_OE_EVENT = "SET_OE_EVENT";
export const SET_CURRENT_PURCHASE = "SET_CURRENT_PURCHASE"
export const CLEAR_CURRENT_PURCHASE = "CLEAR_CURRENT_PURCHASE"
export const EDIT_MODE = "EDIT_MODE"